#!/usr/bin/env python3
import sys
import os
import setup
import add_files
import git
import restore


def main():
    print(f"argv: {sys.argv}")
    setup.startup_checks()
    os.chdir(os.environ["HOME"])
    if len(sys.argv) >= 2:
        switch_based_on_flag(sys.argv[1])
    else:
        print("usage dot-filer -a <file name>")


def switch_based_on_flag(flag):
    switch = {
        "-a": pass_files_to_add_files,
        "add": pass_files_to_add_files,
        "-g": git.git_module,
        "git": git.git_module,
        "-r": restore.restore,
        "restore": restore.restore,
    }
    print(f"switch flag: {flag}")
    # TODO should add help promt here when help file written
    switch[flag]()
    # switch.get(flag, "invalid input")


def pass_files_to_add_files():
    for file in range(2, len(sys.argv)):
        add_files.add_file(sys.argv[file])


def log_restore():
    print("restoring")


if __name__ == "__main__":
    main()
